In [2]:
import numpy as np

In [3]:
l = [1,2,3,4,5]

In [4]:
# To create an array
arr = np.array(l)

In [5]:
type(arr)

numpy.ndarray

In [6]:
# Another way to create an array
np.asarray(l)

array([1, 2, 3, 4, 5])

In [7]:
arr1 = np.array([[1,2,3],[2,3,4]])

In [8]:
# To check the dimension of the array 
arr.ndim

1

In [9]:
# This is 2dimension array
arr1.ndim

2

In [10]:
arr

array([1, 2, 3, 4, 5])

In [11]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [12]:
# this fucntion will automatically return 2 dimension
mat = np.matrix(l)

In [13]:
#this function which will convert anything into array
np.asanyarray(l)

array([1, 2, 3, 4, 5])

In [14]:
np.asanyarray(mat)

matrix([[1, 2, 3, 4, 5]])

In [15]:
a = arr

In [16]:
a

array([1, 2, 3, 4, 5])

In [17]:
arr

array([1, 2, 3, 4, 5])

In [18]:
# this kind of operation which is permanently changed is call shallow copy operation.
arr[0] = 100

In [19]:
a

array([100,   2,   3,   4,   5])

In [20]:
arr

array([100,   2,   3,   4,   5])

In [21]:
# this will create a new memory and assigns a new value this is called deep copy.
b = np.copy(arr)

In [22]:
b[0]=234

In [23]:
b

array([234,   2,   3,   4,   5])

In [24]:
a

array([100,   2,   3,   4,   5])

In [25]:
arr

array([100,   2,   3,   4,   5])

In [26]:
# this is a kind of function in which we will generate a new data set 
np.fromfunction(lambda i, j : i==j, (4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [27]:
np.fromfunction(lambda i, j : i*j, (4,4))

array([[0., 0., 0., 0.],
       [0., 1., 2., 3.],
       [0., 2., 4., 6.],
       [0., 3., 6., 9.]])

In [28]:
np.fromfunction(lambda i, j : i+j, (4,4))

array([[0., 1., 2., 3.],
       [1., 2., 3., 4.],
       [2., 3., 4., 5.],
       [3., 4., 5., 6.]])

In [29]:
list(i*i for i in range(5))

[0, 1, 4, 9, 16]

In [30]:
iterable = ( i*i for i in range(5))

In [31]:
np.fromiter(iterable,int)

array([ 0,  1,  4,  9, 16])

In [32]:
np.fromstring("23 23 45 566", sep = ' ')

array([ 23.,  23.,  45., 566.])

In [33]:
np.fromstring("23, 23, 45 ,566", sep = ' , ')

array([ 23.,  23.,  45., 566.])

In [34]:
arr

array([100,   2,   3,   4,   5])

In [35]:
arr1

array([[1, 2, 3],
       [2, 3, 4]])

In [36]:
arr.ndim

1

In [37]:
arr.size

5

In [38]:
arr1.size

6

In [39]:
arr.shape

(5,)

In [40]:
arr1.shape

(2, 3)

In [41]:
arr.dtype

dtype('int64')

In [42]:
arr1.dtype

dtype('int64')

In [43]:
list (range (5))

[0, 1, 2, 3, 4]

In [44]:
list (range (0, 5))

[0, 1, 2, 3, 4]

In [45]:
# float can be interpreted
list (range (0.4, 10.4))

TypeError: 'float' object cannot be interpreted as an integer

In [46]:
# using numpy we can interprete float as well and also we can give step size
list(np.arange(0.4,10.4,0.2))

[0.4,
 0.6000000000000001,
 0.8000000000000002,
 1.0000000000000002,
 1.2000000000000002,
 1.4000000000000004,
 1.6000000000000005,
 1.8000000000000003,
 2.0000000000000004,
 2.2000000000000006,
 2.400000000000001,
 2.6000000000000005,
 2.8000000000000007,
 3.000000000000001,
 3.2000000000000006,
 3.400000000000001,
 3.600000000000001,
 3.800000000000001,
 4.000000000000002,
 4.200000000000001,
 4.400000000000002,
 4.600000000000001,
 4.800000000000002,
 5.000000000000002,
 5.200000000000002,
 5.400000000000002,
 5.600000000000002,
 5.8000000000000025,
 6.000000000000002,
 6.200000000000002,
 6.400000000000002,
 6.600000000000002,
 6.8000000000000025,
 7.000000000000003,
 7.200000000000003,
 7.400000000000003,
 7.600000000000003,
 7.8000000000000025,
 8.000000000000002,
 8.200000000000003,
 8.400000000000004,
 8.600000000000003,
 8.800000000000002,
 9.000000000000004,
 9.200000000000003,
 9.400000000000004,
 9.600000000000003,
 9.800000000000004,
 10.000000000000004,
 10.20000000000000

In [47]:
np.arange(0.4,10.4,0.2)

array([ 0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,  2.2,  2.4,
        2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,  4.4,  4.6,
        4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,  6.6,  6.8,
        7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,  8.8,  9. ,
        9.2,  9.4,  9.6,  9.8, 10. , 10.2])

In [48]:
# By using this function we can divdie the range of 1,5 into 20 divisions.
np.linspace(1,5,20)

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [49]:
#By using this function we can divdie the range by using log of 1,5 into 20 divisions.
np.logspace(1,5,20, base =2)

array([ 2.        ,  2.31422047,  2.6778082 ,  3.09851928,  3.58532838,
        4.14862018,  4.80041088,  5.55460457,  6.42728981,  7.43708284,
        8.60552469,  9.95754072, 11.5219723 , 13.3321921 , 15.42681597,
       17.85052668, 20.65502717, 23.90014339, 27.65510059, 32.        ])

In [50]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [51]:
# It will generate data with 3 rows and 4 columns
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [52]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [53]:
# but we will not be able to coordinate this into the system 
np.zeros((3,4,2,3))

array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]])

In [54]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [55]:
rrr = np.ones((3,4))

In [56]:
rrr+5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [57]:
rrr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [58]:
rrr*4

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [59]:
np.empty((3,4))

array([[4., 4., 4., 4.],
       [4., 4., 4., 4.],
       [4., 4., 4., 4.]])

In [60]:
# IDENTITY matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [61]:
arr2 = np.eye(5)

In [62]:
import pandas as pd
df = pd.DataFrame(arr2)

In [63]:
df 

0    1    2    3    4
0  1.0  0.0  0.0  0.0  0.0
1  0.0  1.0  0.0  0.0  0.0
2  0.0  0.0  1.0  0.0  0.0
3  0.0  0.0  0.0  1.0  0.0
4  0.0  0.0  0.0  0.0  1.0

In [64]:
np.random.rand(2,3)

array([[0.59421914, 0.10495075, 0.31071165],
       [0.60152181, 0.00894332, 0.55199433]])

In [65]:
# the difference between rand and randn is the mean is 0 and sd is 1 in randn
np.random.randn(2,3)

array([[ 0.27004277, -1.27822295,  0.50059705],
       [ 2.7531827 , -1.58942597, -0.30779288]])

In [66]:
arr2 = np.random.randint(1,5,(3,4))

In [67]:
arr2.size

12

In [68]:
arr2.shape

(3, 4)

In [69]:
arr2.reshape(6,2)

array([[3, 4],
       [1, 2],
       [2, 1],
       [1, 3],
       [4, 3],
       [4, 1]])

In [70]:
arr2.reshape(12,1)

array([[3],
       [4],
       [1],
       [2],
       [2],
       [1],
       [1],
       [3],
       [4],
       [3],
       [4],
       [1]])

In [71]:
arr2.reshape(4,-454)

array([[3, 4, 1],
       [2, 2, 1],
       [1, 3, 4],
       [3, 4, 1]])

In [72]:
arr2.reshape(2,2,3)

array([[[3, 4, 1],
        [2, 2, 1]],

       [[1, 3, 4],
        [3, 4, 1]]])

In [73]:
arr1 = np.random.randint(1,10,(5,6))

In [74]:
arr1

array([[9, 4, 5, 9, 7, 2],
       [3, 5, 2, 7, 3, 4],
       [1, 8, 8, 5, 8, 2],
       [4, 3, 8, 3, 9, 6],
       [4, 9, 2, 9, 2, 3]])

In [75]:
arr1 > 8

array([[ True, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False, False,  True, False],
       [False,  True, False,  True, False, False]])

In [76]:
arr1[arr1 > 8]

array([9, 9, 9, 9, 9])

In [77]:
arr1[0]

array([9, 4, 5, 9, 7, 2])

In [78]:
# If you want to extract particular data from the matrix
arr1[2:4,[2,3]]

array([[8, 5],
       [8, 3]])

In [79]:
arr1[0,[0,1]]

array([9, 4])

In [80]:
arr1= np.random.randint(1,3,(3,3))
arr2= np.random.randint(1,3,(3,3))

In [81]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [82]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [83]:
arr1+arr2

array([[3, 3, 3],
       [3, 3, 2],
       [2, 3, 3]])

In [84]:
# Index wise multiplication
arr1*arr2

array([[2, 2, 2],
       [2, 2, 1],
       [1, 2, 2]])

In [85]:
arr1-arr2

array([[-1, -1,  1],
       [ 1,  1,  0],
       [ 0,  1, -1]])

In [86]:
arr1

array([[1, 1, 2],
       [2, 2, 1],
       [1, 2, 1]])

In [87]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [1, 1, 2]])

In [88]:
# Matrix multiplication
arr1@arr2

array([[5, 5, 6],
       [7, 7, 6],
       [5, 5, 5]])

In [89]:
arr1/arr2

array([[0.5, 0.5, 2. ],
       [2. , 2. , 1. ],
       [1. , 2. , 0.5]])

In [90]:
arr1/0

/tmp/ipykernel_102/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [91]:
# Numpy - Broadcasting.
arr = np.zeros((3,4))

In [92]:
arr+5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [93]:
a = np.array([1,2,3,4])

In [94]:
arr+a

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [95]:
b = np.array([3,4,5])

In [96]:
arr1 = arr1+b.T

In [97]:
b.T

array([3, 4, 5])

In [98]:
np.sqrt(arr1)

array([[2.        , 2.23606798, 2.64575131],
       [2.23606798, 2.44948974, 2.44948974],
       [2.        , 2.44948974, 2.44948974]])

In [99]:
np.log10(arr1)

array([[0.60205999, 0.69897   , 0.84509804],
       [0.69897   , 0.77815125, 0.77815125],
       [0.60205999, 0.77815125, 0.77815125]])

In [100]:
np.exp(arr1)

array([[  54.59815003,  148.4131591 , 1096.63315843],
       [ 148.4131591 ,  403.42879349,  403.42879349],
       [  54.59815003,  403.42879349,  403.42879349]])

In [101]:
np.min(arr1)

4

In [102]:
np.max(arr1)

7

In [103]:
# Arrary manipulation
arr = np.random.randint(1,10,(4,4))
arr

array([[6, 5, 4, 9],
       [4, 2, 7, 7],
       [4, 6, 6, 4],
       [4, 1, 6, 3]])

In [104]:
arr.reshape(8,2)

array([[6, 5],
       [4, 9],
       [4, 2],
       [7, 7],
       [4, 6],
       [6, 4],
       [4, 1],
       [6, 3]])

In [105]:
arr.T

array([[6, 4, 4, 4],
       [5, 2, 6, 1],
       [4, 7, 6, 6],
       [9, 7, 4, 3]])

In [106]:
arr.flatten()

array([6, 5, 4, 9, 4, 2, 7, 7, 4, 6, 6, 4, 4, 1, 6, 3])

In [107]:
# it has expanded to 3 dimensions
np.expand_dims(arr, axis =1)

array([[[6, 5, 4, 9]],

       [[4, 2, 7, 7]],

       [[4, 6, 6, 4]],

       [[4, 1, 6, 3]]])

In [108]:
np.expand_dims(arr, axis =1)

array([[[6, 5, 4, 9]],

       [[4, 2, 7, 7]],

       [[4, 6, 6, 4]],

       [[4, 1, 6, 3]]])

In [109]:
data = np.array([[1],[2],[3]])

In [110]:
np.squeeze(data)

array([1, 2, 3])

In [111]:
np.repeat(data,2)

array([1, 1, 2, 2, 3, 3])

In [112]:
np.repeat(data,4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [113]:
# Here it is trying to roll the data
np.roll(data,2)

array([[2],
       [3],
       [1]])

In [114]:
# diagonal values are in the matrix
np.diag(np.array([1,2,3,4]))

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [115]:
# Binary Operations
arr1 = np.random.randint(1,10,(3,4))
arr2 = np.random.randint(1,10,(3,4))

In [116]:
arr1

array([[8, 2, 1, 1],
       [5, 6, 1, 1],
       [4, 6, 7, 3]])

In [117]:
arr2

array([[8, 1, 9, 4],
       [9, 1, 9, 7],
       [3, 5, 5, 7]])

In [118]:
arr1 + arr2

array([[16,  3, 10,  5],
       [14,  7, 10,  8],
       [ 7, 11, 12, 10]])

In [119]:
arr1 * arr2

array([[64,  2,  9,  4],
       [45,  6,  9,  7],
       [12, 30, 35, 21]])

In [120]:
arr1 / arr2

array([[1.        , 2.        , 0.11111111, 0.25      ],
       [0.55555556, 6.        , 0.11111111, 0.14285714],
       [1.33333333, 1.2       , 1.4       , 0.42857143]])

In [121]:
arr1 - arr2

array([[ 0,  1, -8, -3],
       [-4,  5, -8, -6],
       [ 1,  1,  2, -4]])

In [122]:
arr1 ** arr2

array([[16777216,        2,        1,        1],
       [ 1953125,        6,        1,        1],
       [      64,     7776,    16807,     2187]])

In [123]:
arr1

array([[8, 2, 1, 1],
       [5, 6, 1, 1],
       [4, 6, 7, 3]])

In [124]:
~arr1

array([[-9, -3, -2, -2],
       [-6, -7, -2, -2],
       [-5, -7, -8, -4]])

In [125]:
arr1>arr2

array([[False,  True, False, False],
       [False,  True, False, False],
       [ True,  True,  True, False]])

In [126]:
# Numpy - String Functions.
arr = np.array(["rakesh","Etikala"])

In [127]:
arr

array(['rakesh', 'Etikala'], dtype='<U7')

In [128]:
np.char.upper(arr)

array(['RAKESH', 'ETIKALA'], dtype='<U7')

In [129]:
np.char.capitalize(arr)

array(['Rakesh', 'Etikala'], dtype='<U7')

In [130]:
np.char.lower(arr)

array(['rakesh', 'etikala'], dtype='<U7')

In [131]:
np.char.title(arr)

array(['Rakesh', 'Etikala'], dtype='<U7')

In [132]:
# Numpy -  Mathematical Functions.

In [133]:
arr1 

array([[8, 2, 1, 1],
       [5, 6, 1, 1],
       [4, 6, 7, 3]])

In [134]:
np.sin(arr1)

array([[ 0.98935825,  0.90929743,  0.84147098,  0.84147098],
       [-0.95892427, -0.2794155 ,  0.84147098,  0.84147098],
       [-0.7568025 , -0.2794155 ,  0.6569866 ,  0.14112001]])

In [135]:
np.cos(arr1)

array([[-0.14550003, -0.41614684,  0.54030231,  0.54030231],
       [ 0.28366219,  0.96017029,  0.54030231,  0.54030231],
       [-0.65364362,  0.96017029,  0.75390225, -0.9899925 ]])

In [136]:
np.tan(arr1)

array([[-6.79971146, -2.18503986,  1.55740772,  1.55740772],
       [-3.38051501, -0.29100619,  1.55740772,  1.55740772],
       [ 1.15782128, -0.29100619,  0.87144798, -0.14254654]])

In [137]:
np.log10(arr1)

array([[0.90308999, 0.30103   , 0.        , 0.        ],
       [0.69897   , 0.77815125, 0.        , 0.        ],
       [0.60205999, 0.77815125, 0.84509804, 0.47712125]])

In [138]:
np.exp(arr1)

array([[2.98095799e+03, 7.38905610e+00, 2.71828183e+00, 2.71828183e+00],
       [1.48413159e+02, 4.03428793e+02, 2.71828183e+00, 2.71828183e+00],
       [5.45981500e+01, 4.03428793e+02, 1.09663316e+03, 2.00855369e+01]])

In [139]:
np.power(arr1,2)

array([[64,  4,  1,  1],
       [25, 36,  1,  1],
       [16, 36, 49,  9]])

In [140]:
np.mean(arr1)

3.75

In [141]:
np.median(arr1)

3.5

In [142]:
np.std(arr1)

2.48746859276655

In [143]:
np.var(arr1)

6.1875

In [144]:
np.min(arr1)

1

In [145]:
np.max(arr1)

8

In [146]:
# Numpy - Arithmetic - operations

In [147]:
arr2 

array([[8, 1, 9, 4],
       [9, 1, 9, 7],
       [3, 5, 5, 7]])

In [148]:
arr1

array([[8, 2, 1, 1],
       [5, 6, 1, 1],
       [4, 6, 7, 3]])

In [149]:
arr1- arr2

array([[ 0,  1, -8, -3],
       [-4,  5, -8, -6],
       [ 1,  1,  2, -4]])

In [150]:
np.subtract(arr1,arr2)

array([[ 0,  1, -8, -3],
       [-4,  5, -8, -6],
       [ 1,  1,  2, -4]])

In [151]:
np.multiply(arr1,arr2)

array([[64,  2,  9,  4],
       [45,  6,  9,  7],
       [12, 30, 35, 21]])

In [152]:
np.mod(arr1,arr2)

array([[0, 0, 1, 1],
       [5, 0, 1, 1],
       [1, 1, 2, 3]])

In [153]:
np.power(arr1,arr2)

array([[16777216,        2,        1,        1],
       [ 1953125,        6,        1,        1],
       [      64,     7776,    16807,     2187]])

In [154]:
np.sqrt(arr1)

array([[2.82842712, 1.41421356, 1.        , 1.        ],
       [2.23606798, 2.44948974, 1.        , 1.        ],
       [2.        , 2.44948974, 2.64575131, 1.73205081]])

In [155]:
np.mean(arr1)

3.75

In [156]:
np.std(arr1)

2.48746859276655

In [159]:
# sort search and cutting functions
arr =np.array([2,3,4,5,6])

In [160]:
np.sort(arr)

array([2, 3, 4, 5, 6])

In [161]:
np.searchsorted(arr, 6)

4

In [ ]:
arr1 = np.array([0,5,2,4,5,6,7,8,9,52,4,5,5,,9,])

In [162]:
np.count_nonzero(arr1)

12

In [164]:
np.where(arr1 >0)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2]),
 array([0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [171]:
np.extract(arr1 > 2, arr1)

array([8, 5, 6, 4, 6, 7, 3])

In [183]:
# Byte Swaping
df = np.array([1,2,3,4,5,6,8,5,7,48,9,9,6])

In [184]:
df

array([ 1,  2,  3,  4,  5,  6,  8,  5,  7, 48,  9,  9,  6])

In [185]:
df.byteswap()

array([  72057594037927936,  144115188075855872,  216172782113783808,
        288230376151711744,  360287970189639680,  432345564227567616,
        576460752303423488,  360287970189639680,  504403158265495552,
       3458764513820540928,  648518346341351424,  648518346341351424,
        432345564227567616])

In [186]:
df

array([ 1,  2,  3,  4,  5,  6,  8,  5,  7, 48,  9,  9,  6])

In [190]:
# Numpy Copies & Views
df

array([ 1,  2,  3,  4,  5,  6,  8,  5,  7, 48,  9,  9,  6])

In [199]:
# Deep Copy
a = np.copy(df)

In [200]:
# Shallow copy
b = df.view()

In [201]:
b

array([234,   2,   3,   4,   5,   6,   8,   5,   7,  48,   9,   9,   6])

In [202]:
b[0] = 234

In [203]:
b

array([234,   2,   3,   4,   5,   6,   8,   5,   7,  48,   9,   9,   6])

In [204]:
df

array([234,   2,   3,   4,   5,   6,   8,   5,   7,  48,   9,   9,   6])

In [198]:
b= df

In [205]:
# Numpy - Matrix Library.

In [208]:
import numpy.matlib as nm

In [210]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [211]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [212]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [213]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [214]:
nm.eye(4)

matrix([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 1.]])

In [215]:
# Linear Algebra

In [218]:
df

array([234,   2,   3,   4,   5,   6,   8,   5,   7,  48,   9,   9,   6])

In [220]:
arr2 = np.random.randint([(2,3),[4,5]])

In [221]:
arr3 = np.random.randint([(5,3),[2,5]])

In [223]:
arr2

array([[1, 0],
       [1, 4]])

In [224]:
arr2

array([[1, 0],
       [1, 4]])